packages:
  - "packages/*"
allowBuilds:
  '@bundled-es-modules/glob': true
  esbuild: set this to true or false
  puppeteer: set this to true or false
  style-dictionary: true
onlyBuiltDependencies:
  - "@bundled-es-modules/glob"
  - "style-dictionary"
