packages:
  - "packages/*"
allowBuilds:
  '@bundled-es-modules/glob': true
  esbuild: true
  puppeteer: true
  style-dictionary: true
dangerouslyAllowAllBuilds: true
onlyBuiltDependencies:
  - "@bundled-es-modules/glob"
  - "style-dictionary"
