/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
    }
    interface DsCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
    }
    interface DsInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsSelect {
        /**
          * @default ''
         */
        "value": string;
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsCheckboxElement extends Components.DsCheckbox, HTMLStencilElement {
    }
    var HTMLDsCheckboxElement: {
        prototype: HTMLDsCheckboxElement;
        new (): HTMLDsCheckboxElement;
    };
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLDsSelectElement extends Components.DsSelect, HTMLStencilElement {
    }
    var HTMLDsSelectElement: {
        prototype: HTMLDsSelectElement;
        new (): HTMLDsSelectElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-checkbox": HTMLDsCheckboxElement;
        "ds-input": HTMLDsInputElement;
        "ds-select": HTMLDsSelectElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    interface DsCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
    }
    interface DsInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsSelect {
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface DsButtonAttributes {
        "type": 'button' | 'submit' | 'reset';
        "disabled": boolean;
    }
    interface DsCheckboxAttributes {
        "checked": boolean;
        "disabled": boolean;
    }
    interface DsInputAttributes {
        "value": string;
        "placeholder": string;
        "disabled": boolean;
    }
    interface DsSelectAttributes {
        "value": string;
    }

    interface IntrinsicElements {
        "ds-button": Omit<DsButton, keyof DsButtonAttributes> & { [K in keyof DsButton & keyof DsButtonAttributes]?: DsButton[K] } & { [K in keyof DsButton & keyof DsButtonAttributes as `attr:${K}`]?: DsButtonAttributes[K] } & { [K in keyof DsButton & keyof DsButtonAttributes as `prop:${K}`]?: DsButton[K] };
        "ds-checkbox": Omit<DsCheckbox, keyof DsCheckboxAttributes> & { [K in keyof DsCheckbox & keyof DsCheckboxAttributes]?: DsCheckbox[K] } & { [K in keyof DsCheckbox & keyof DsCheckboxAttributes as `attr:${K}`]?: DsCheckboxAttributes[K] } & { [K in keyof DsCheckbox & keyof DsCheckboxAttributes as `prop:${K}`]?: DsCheckbox[K] };
        "ds-input": Omit<DsInput, keyof DsInputAttributes> & { [K in keyof DsInput & keyof DsInputAttributes]?: DsInput[K] } & { [K in keyof DsInput & keyof DsInputAttributes as `attr:${K}`]?: DsInputAttributes[K] } & { [K in keyof DsInput & keyof DsInputAttributes as `prop:${K}`]?: DsInput[K] };
        "ds-select": Omit<DsSelect, keyof DsSelectAttributes> & { [K in keyof DsSelect & keyof DsSelectAttributes]?: DsSelect[K] } & { [K in keyof DsSelect & keyof DsSelectAttributes as `attr:${K}`]?: DsSelectAttributes[K] } & { [K in keyof DsSelect & keyof DsSelectAttributes as `prop:${K}`]?: DsSelect[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.IntrinsicElements["ds-button"] & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-checkbox": LocalJSX.IntrinsicElements["ds-checkbox"] & JSXBase.HTMLAttributes<HTMLDsCheckboxElement>;
            "ds-input": LocalJSX.IntrinsicElements["ds-input"] & JSXBase.HTMLAttributes<HTMLDsInputElement>;
            "ds-select": LocalJSX.IntrinsicElements["ds-select"] & JSXBase.HTMLAttributes<HTMLDsSelectElement>;
        }
    }
}
